Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "C:/Users/12137/Desktop/source code/FL_image_classification备份/main.py", line 40, in <module>
    diff = c.local_train(server.global_model)  # Perform local training and calculate the difference dictionary
  File "C:\Users\12137\Desktop\source code\FL_image_classification备份\client.py", line 49, in local_train
    output = self.local_model(data)
  File "C:\Users\12137\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\12137\Desktop\source code\FL_image_classification备份\model.py", line 59, in forward
    out = F.relu(self.bn1(self.conv1(x)))
  File "C:\Users\12137\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\12137\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\12137\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution